# Generated by Django 4.0.3 on 2022-03-16 21:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('abbreviation', models.CharField(max_length=4)),
            ],
            options={
                'db_table': 'document_type',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_number', models.BigIntegerField(unique=True)),
                ('second_name', models.CharField(blank=True, max_length=30, null=True)),
                ('second_lastname', models.CharField(blank=True, max_length=30, null=True)),
                ('profession', models.CharField(max_length=100)),
                ('profile', models.TextField()),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.documenttype')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_app',
                'managed': True,
            },
        ),
    ]
