# Generated by Django 4.0.3 on 2022-03-16 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_authgroup_authgrouppermissions_authpermission_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'status',
                'managed': True,
            },
        ),
        migrations.AlterModelOptions(
            name='documenttype',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='userapp',
            options={'managed': True},
        ),
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('salary', models.DecimalField(decimal_places=2, max_digits=15)),
                ('creation_date', models.DateTimeField(auto_now=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('creator_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to='core.userapp')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.status')),
                ('updater_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='updater', to='core.userapp')),
            ],
            options={
                'db_table': 'offer',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Postulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now=True)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.offers')),
                ('user_app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.userapp')),
            ],
            options={
                'db_table': 'postulation',
                'managed': True,
                'unique_together': {('offer', 'user_app')},
            },
        ),
    ]
