# Generated by Django 4.0.3 on 2022-03-17 03:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_alter_offers_creation_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postulation',
            old_name='user_app',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='postulation',
            unique_together={('offer', 'user')},
        ),
    ]
